# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Dec 22 23:10:35 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 601)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlVLayout = QtGui.QVBoxLayout()
        self.controlVLayout.setObjectName("controlVLayout")
        self.acquisitionBox = QtGui.QGroupBox(self.centralwidget)
        self.acquisitionBox.setObjectName("acquisitionBox")
        self.formLayout_2 = QtGui.QFormLayout(self.acquisitionBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtGui.QLabel(self.acquisitionBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.modeCombo = QtGui.QComboBox(self.acquisitionBox)
        self.modeCombo.setObjectName("modeCombo")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.modeCombo)
        self.label_2 = QtGui.QLabel(self.acquisitionBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.nbSensors = QtGui.QSpinBox(self.acquisitionBox)
        self.nbSensors.setEnabled(False)
        self.nbSensors.setProperty("value", 8)
        self.nbSensors.setObjectName("nbSensors")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.nbSensors)
        self.controlVLayout.addWidget(self.acquisitionBox)
        self.transformBox = QtGui.QGroupBox(self.centralwidget)
        self.transformBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.transformBox.setObjectName("transformBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.transformBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.transformBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.transformBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.controlVLayout.addWidget(self.transformBox)
        self.displayBox = QtGui.QGroupBox(self.centralwidget)
        self.displayBox.setObjectName("displayBox")
        self.gridLayout = QtGui.QGridLayout(self.displayBox)
        self.gridLayout.setObjectName("gridLayout")
        self.show1 = QtGui.QCheckBox(self.displayBox)
        self.show1.setChecked(True)
        self.show1.setObjectName("show1")
        self.gridLayout.addWidget(self.show1, 0, 0, 1, 1)
        self.show2 = QtGui.QCheckBox(self.displayBox)
        self.show2.setChecked(True)
        self.show2.setObjectName("show2")
        self.gridLayout.addWidget(self.show2, 0, 1, 1, 1)
        self.show3 = QtGui.QCheckBox(self.displayBox)
        self.show3.setChecked(True)
        self.show3.setObjectName("show3")
        self.gridLayout.addWidget(self.show3, 1, 0, 1, 1)
        self.show4 = QtGui.QCheckBox(self.displayBox)
        self.show4.setChecked(True)
        self.show4.setObjectName("show4")
        self.gridLayout.addWidget(self.show4, 1, 1, 1, 1)
        self.show5 = QtGui.QCheckBox(self.displayBox)
        self.show5.setChecked(True)
        self.show5.setObjectName("show5")
        self.gridLayout.addWidget(self.show5, 2, 0, 1, 1)
        self.show6 = QtGui.QCheckBox(self.displayBox)
        self.show6.setChecked(True)
        self.show6.setObjectName("show6")
        self.gridLayout.addWidget(self.show6, 2, 1, 1, 1)
        self.show7 = QtGui.QCheckBox(self.displayBox)
        self.show7.setChecked(True)
        self.show7.setObjectName("show7")
        self.gridLayout.addWidget(self.show7, 3, 0, 1, 1)
        self.show8 = QtGui.QCheckBox(self.displayBox)
        self.show8.setChecked(True)
        self.show8.setObjectName("show8")
        self.gridLayout.addWidget(self.show8, 3, 1, 1, 1)
        self.controlVLayout.addWidget(self.displayBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.controlVLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startStopButton = QtGui.QPushButton(self.centralwidget)
        self.startStopButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.startStopButton.setObjectName("startStopButton")
        self.horizontalLayout_2.addWidget(self.startStopButton)
        self.resetButton = QtGui.QPushButton(self.centralwidget)
        self.resetButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_2.addWidget(self.resetButton)
        self.controlVLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.controlVLayout)
        self.placeholder = QtGui.QWidget(self.centralwidget)
        self.placeholder.setObjectName("placeholder")
        self.horizontalLayout.addWidget(self.placeholder)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Load = QtGui.QAction(MainWindow)
        self.action_Load.setObjectName("action_Load")
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.menuFile.addAction(self.action_Load)
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_Quit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.acquisitionBox.setTitle(QtGui.QApplication.translate("MainWindow", "Acquisition", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Nb sensors", None, QtGui.QApplication.UnicodeUTF8))
        self.transformBox.setTitle(QtGui.QApplication.translate("MainWindow", "Transform", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "f(x) = ", None, QtGui.QApplication.UnicodeUTF8))
        self.displayBox.setTitle(QtGui.QApplication.translate("MainWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.show1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.show2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.show3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.show4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.show5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.show6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.show7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.show8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.startStopButton.setText(QtGui.QApplication.translate("MainWindow", "&Start", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("MainWindow", "&Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load.setText(QtGui.QApplication.translate("MainWindow", "&Load", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))

