# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Jan  6 23:47:27 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 601)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlVLayout = QtGui.QVBoxLayout()
        self.controlVLayout.setObjectName("controlVLayout")
        self.transformBox = QtGui.QGroupBox(self.centralwidget)
        self.transformBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.transformBox.setObjectName("transformBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.transformBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.transformBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.transformBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.controlVLayout.addWidget(self.transformBox)
        self.displayPanelContainer = QtGui.QWidget(self.centralwidget)
        self.displayPanelContainer.setMinimumSize(QtCore.QSize(0, 20))
        self.displayPanelContainer.setObjectName("displayPanelContainer")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.displayPanelContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.displayPanelContainer)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.show6 = QtGui.QCheckBox(self.displayPanelContainer)
        self.show6.setChecked(True)
        self.show6.setObjectName("show6")
        self.gridLayout.addWidget(self.show6, 3, 1, 1, 1)
        self.show1 = QtGui.QCheckBox(self.displayPanelContainer)
        self.show1.setChecked(True)
        self.show1.setObjectName("show1")
        self.gridLayout.addWidget(self.show1, 1, 0, 1, 1)
        self.show8 = QtGui.QCheckBox(self.displayPanelContainer)
        self.show8.setChecked(True)
        self.show8.setObjectName("show8")
        self.gridLayout.addWidget(self.show8, 4, 1, 1, 1)
        self.show5 = QtGui.QCheckBox(self.displayPanelContainer)
        self.show5.setChecked(True)
        self.show5.setObjectName("show5")
        self.gridLayout.addWidget(self.show5, 3, 0, 1, 1)
        self.show7 = QtGui.QCheckBox(self.displayPanelContainer)
        self.show7.setChecked(True)
        self.show7.setObjectName("show7")
        self.gridLayout.addWidget(self.show7, 4, 0, 1, 1)
        self.show3 = QtGui.QCheckBox(self.displayPanelContainer)
        self.show3.setChecked(True)
        self.show3.setObjectName("show3")
        self.gridLayout.addWidget(self.show3, 2, 0, 1, 1)
        self.show2 = QtGui.QCheckBox(self.displayPanelContainer)
        self.show2.setChecked(True)
        self.show2.setObjectName("show2")
        self.gridLayout.addWidget(self.show2, 1, 1, 1, 1)
        self.show4 = QtGui.QCheckBox(self.displayPanelContainer)
        self.show4.setChecked(True)
        self.show4.setObjectName("show4")
        self.gridLayout.addWidget(self.show4, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.columnsSpinBox = QtGui.QSpinBox(self.displayPanelContainer)
        self.columnsSpinBox.setMinimum(1)
        self.columnsSpinBox.setProperty("value", 3)
        self.columnsSpinBox.setObjectName("columnsSpinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.columnsSpinBox)
        self.label_4 = QtGui.QLabel(self.displayPanelContainer)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.showTiming = QtGui.QCheckBox(self.displayPanelContainer)
        self.showTiming.setText("")
        self.showTiming.setChecked(True)
        self.showTiming.setObjectName("showTiming")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.showTiming)
        self.showMaster = QtGui.QCheckBox(self.displayPanelContainer)
        self.showMaster.setText("")
        self.showMaster.setObjectName("showMaster")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.showMaster)
        self.label_5 = QtGui.QLabel(self.displayPanelContainer)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.displayPanelContainer)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.displayPanelContainer)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.showTitles = QtGui.QCheckBox(self.displayPanelContainer)
        self.showTitles.setText("")
        self.showTitles.setObjectName("showTitles")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.showTitles)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.controlVLayout.addWidget(self.displayPanelContainer)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.controlVLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startStopButton = QtGui.QPushButton(self.centralwidget)
        self.startStopButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.startStopButton.setObjectName("startStopButton")
        self.horizontalLayout_2.addWidget(self.startStopButton)
        self.resetButton = QtGui.QPushButton(self.centralwidget)
        self.resetButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_2.addWidget(self.resetButton)
        self.controlVLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.controlVLayout)
        self.placeholder = QtGui.QWidget(self.centralwidget)
        self.placeholder.setObjectName("placeholder")
        self.horizontalLayout.addWidget(self.placeholder)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuMode = QtGui.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        self.menuAcquisition = QtGui.QMenu(self.menuMode)
        self.menuAcquisition.setObjectName("menuAcquisition")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Load = QtGui.QAction(MainWindow)
        self.action_Load.setObjectName("action_Load")
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.actionSerial_Acquisition = QtGui.QAction(MainWindow)
        self.actionSerial_Acquisition.setCheckable(True)
        self.actionSerial_Acquisition.setChecked(False)
        self.actionSerial_Acquisition.setObjectName("actionSerial_Acquisition")
        self.actionFake_Acquisition = QtGui.QAction(MainWindow)
        self.actionFake_Acquisition.setCheckable(True)
        self.actionFake_Acquisition.setChecked(True)
        self.actionFake_Acquisition.setObjectName("actionFake_Acquisition")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDisplay = QtGui.QAction(MainWindow)
        self.actionDisplay.setCheckable(True)
        self.actionDisplay.setChecked(True)
        self.actionDisplay.setObjectName("actionDisplay")
        self.menuFile.addAction(self.action_Load)
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_Quit)
        self.menuView.addAction(self.actionDisplay)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAcquisition.addAction(self.actionSerial_Acquisition)
        self.menuAcquisition.addAction(self.actionFake_Acquisition)
        self.menuMode.addAction(self.menuAcquisition.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionDisplay, QtCore.SIGNAL("triggered(bool)"), self.displayPanelContainer.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Plots! Plots! Plots!", None, QtGui.QApplication.UnicodeUTF8))
        self.transformBox.setTitle(QtGui.QApplication.translate("MainWindow", "Transform", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "f(x) = ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.show6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.show1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.show8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.show5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.show7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.show3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.show2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.show4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Timing plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Master plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Show titles", None, QtGui.QApplication.UnicodeUTF8))
        self.startStopButton.setText(QtGui.QApplication.translate("MainWindow", "&Start", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("MainWindow", "&Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMode.setTitle(QtGui.QApplication.translate("MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAcquisition.setTitle(QtGui.QApplication.translate("MainWindow", "Acquisition", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load.setText(QtGui.QApplication.translate("MainWindow", "&Load", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSerial_Acquisition.setText(QtGui.QApplication.translate("MainWindow", "Serial Acquisition", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFake_Acquisition.setText(QtGui.QApplication.translate("MainWindow", "Fake Acquisition", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisplay.setText(QtGui.QApplication.translate("MainWindow", "&Display", None, QtGui.QApplication.UnicodeUTF8))

